#include "j2s.h"     // generated by:  gen j2s.proto
#include "co/flag.h"
#include "co/print.h"

int main(int argc, char** argv) {
    flag::parse(argc, argv);

    json::any v;
    v.add_member("b", false)
     .add_member("i", 23)
     .add_member("s", "hello")
     .add_member("data", json::any().add_member("ii", 11).add_member("ss", "good"))
     .add_member("ai", json::any().push_back(1).push_back(2).push_back(3))
     .add_member("ao", json::any().push_back(json::any().add_member("xx", 88).add_member("yy", "nice")));

    co::println("Json v:\n", v, '\n');
    
    xx::XX x;
    x.from_json(v);

    co::println("x.b: ", x.b);
    co::println("x.i: ", x.i);
    co::println("x.s: ", x.s);
    co::println("x.data.ii: ", x.data.ii);
    co::println("x.data.ss: ", x.data.ss);
    co::println("x.ai[0]: ", x.ai[0]);
    co::println("x.ai[1]: ", x.ai[1]);
    co::println("x.ai[2]: ", x.ai[2]);
    co::println("x.ao[0].xx: ", x.ao[0].xx);
    co::println("x.ao[0].yy: ", x.ao[0].yy);

    co::println("\nx.as_json():");
    co::println(x.as_json());

    return 0;
}
