// Autogenerated.
// DO NOT EDIT. All changes will be undone.
#pragma once

#include "co/rpc.h"

namespace xx {

struct HelloAgain : co::rpc_service {
    HelloAgain() {
        using std::placeholders::_1;
        using std::placeholders::_2;
        _methods["HelloAgain.hello"] = std::bind(&HelloAgain::hello, this, _1, _2);
        _methods["HelloAgain.again"] = std::bind(&HelloAgain::again, this, _1, _2);
    }

    virtual ~HelloAgain() {}

    virtual const char* name() const {
        return "HelloAgain";
    }

    virtual const co::map<const char*, co::rpc_method_t>& methods() const {
        return _methods;
    }

    virtual void hello(json::any& req, json::any& res) = 0;

    virtual void again(json::any& req, json::any& res) = 0;

    co::map<const char*, co::rpc_method_t> _methods;
};

} // xx
