#pragma once

#include "string.h"

namespace flag {

// Add alias for a flag, @new_name must have static life cycle.
// If @new_name is empty, the existing alias will be removed.
void alias(const char* name, const char* new_name);

// set default config path
void set_config_path(const char* path);

void set_program_version(const char* ver);

// hide a flag so that it will not be seen in command line (--help) or 
// in the config file generated by -mkconf
void hide(const char* name);

// opposite to hide
void unhide(const char* name);

// set value of a flag
void set_value(const char* flag_name, const char* value);

// add a callback to be called after command line args are parsed
void run_after_parse(void(*cb)());

// add a callback to be called before command line args are parsed
void run_before_parse(void(*cb)());

// Parse both command line args and config file by default, 
// parse command line args only if @command_line_only is true.
co::vector<co::string> parse(int argc, char** argv, bool command_line_only=false);

namespace xx {

struct FlagSaver {
    FlagSaver(
        char type, const char* name, const char* value, const char* help, 
        const char* file, int line, void* addr, const char* alias
    );

    FlagSaver(
        char type, const char* name, const char* value, const char** help, 
        const char* file, int line, void* addr, const char* alias
    );
};

} // xx
} // flag

#define _DEC_FLAG(type, name) extern type FLG_##name;

#define DEC_bool(name)    _DEC_FLAG(bool, name)
#define DEC_int32(name)   _DEC_FLAG(int32, name)
#define DEC_int64(name)   _DEC_FLAG(int64, name)
#define DEC_uint32(name)  _DEC_FLAG(uint32, name)
#define DEC_uint64(name)  _DEC_FLAG(uint64, name)
#define DEC_double(name)  _DEC_FLAG(double, name)
#define DEC_string(name)  extern co::string& FLG_##name

#define _DEF_FLAG(type, iden, name, value, help, ...) \
    type FLG_##name = value; \
    static ::flag::xx::FlagSaver _FLG_saver_##name(\
        iden, #name, #value, help, __FILE__, __LINE__, &FLG_##name, ""#__VA_ARGS__ \
    );

#define DEF_bool(name, value, help, ...)   _DEF_FLAG(bool,   'b', name, value, help, __VA_ARGS__)
#define DEF_int32(name, value, help, ...)  _DEF_FLAG(int32,  'i', name, value, help, __VA_ARGS__)
#define DEF_int64(name, value, help, ...)  _DEF_FLAG(int64,  'I', name, value, help, __VA_ARGS__)
#define DEF_uint32(name, value, help, ...) _DEF_FLAG(uint32, 'u', name, value, help, __VA_ARGS__)
#define DEF_uint64(name, value, help, ...) _DEF_FLAG(uint64, 'U', name, value, help, __VA_ARGS__)
#define DEF_double(name, value, help, ...) _DEF_FLAG(double, 'd', name, value, help, __VA_ARGS__)

#define DEF_string(name, value, help, ...) \
    co::string& FLG_##name = *[]() { \
        auto _##name = ::co::_make_static<co::string>(value); \
        ::flag::xx::FlagSaver _s_##name( \
            's', #name, #value, help, __FILE__, __LINE__, _##name, ""#__VA_ARGS__ \
        ); \
        return _##name; \
    }();
