name: Windows-arm64

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-windows-arm64:
    runs-on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify arch
        run: echo "PROCESSOR_ARCHITECTURE=$env:PROCESSOR_ARCHITECTURE"

      - name: Configure
        run: cmake -S . -B cmakebuild -A ARM64 -DBUILD_ALL=ON

      - name: Build
        run: cmake --build cmakebuild --config Release --parallel 8

      - name: Run tests
        run: |
          cd cmakebuild\bin\Release
          .\unitest.exe
          .\co.exe
          .\os.exe
